#!/usr/bin/python

import os,time
import webbrowser


os.system("sudo add-apt-repository -y ppa:webupd8team/java")
os.system("clear")

print("=================Installation===================")
print("====================For=========================")
print("===============Required Things==================")
time.sleep(2)
os.system("clear")

print("==================Updating...===================")
time.sleep(1.5)
os.system("sudo apt-get update")
os.system("clear")

print("==================Upgrading...==================")
time.sleep(1.5)
os.system("sudo apt-get upgrade")
os.system("clear")


print("==============Installing Java...================")
time.sleep(1.5)
os.system("sudo apt-get -y install oracle-java8-installer")
os.system("clear")

print("==============Installing Depencies==============")
time.sleep(1.5)
os.system("sudo apt-get install build-essential libreadline-dev libssl-dev libpq5 libpq-dev libreadline5 libsqlite3-dev libpcap-dev git-core autoconf postgresql pgadmin3 curl zlib1g-dev libxml2-dev libxslt1-dev vncviewer libyaml-dev curl zlib1g-dev")        
os.system("clear")

print("===============Installing Ruby=================")
time.sleep(1.5)
os.system("sudo apt-get install ruby-full")
os.system("clear")

print("===============Installing Nmap=================")
time.sleep(1.5)
os.system("sudo apt-get install nmap")
os.system("clear")

print("All the required things are installed")
time.sleep(1.3)
os.system("clear")

print("A window will pop-up and follow the instructions to download Metasploit")
time.sleep(2)
webbrowser.open("https://www.rapid7.com/products/metasploit/download/")
